### ISSUE TITLE
PNG, GIF : File format is not supported

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Rustemt/metadata-extractor#76]
```
What steps will reproduce the problem?
1. Metadata metadata = ImageMetadataReader.readMetadata(this.originalPicture);
this.originalPicture is type File (java.io.File).

What is the expected output? What do you see instead?
com.drew.imaging.ImageProcessingException: File format is not supported
    at com.drew.imaging.ImageMetadataReader.readMetadata(Unknown Source)
    at com.drew.imaging.ImageMetadataReader.readMetadata(Unknown Source)

What version of the product are you using? On what operating system?
v2.6.4, on Windows 7 64bits.

Please provide any additional information below.
I can't see png/gif, management in the source files (I have not looked 
everything yet), but the Home webpage indicate it is possible ..? Did I miss 
something ?

Thanks in advance :)

```

Original issue reported on code.google.com by `mickael....@gmail.com` on 30 Mar 2013 at 11:46

Attachments:
- [RockAlpha_250x250.png](https://storage.googleapis.com/google-code-attachments/metadata-extractor/issue-76/comment-0/RockAlpha_250x250.png)

**Comment by GoogleCodeExporter** [comment]
```
Hi,

I have also encountered the above issue, with png, gif and bmp.
```

Original comment by `hexc...@gmail.com` on 28 Jun 2013 at 12:19

**Comment by GoogleCodeExporter** [comment]
```
Hi,

I have above issue with gif image.
```

Original comment by `idali0...@gmail.com` on 2 Sep 2013 at 7:26

**Comment by GoogleCodeExporter** [comment]
```
Outstanding library. However I've also encountered the problem with png's. Very 
easy to reproduce

File img = new File("c:/ping.png");
Metadata metadata = ImageMetadataReader.readMetadata(img);

Using version 2.6.4
```

Original comment by `ogren.pe...@gmail.com` on 25 Oct 2013 at 10:26

**Comment by GoogleCodeExporter** [comment]
```
com.drew.imaging.ImageProcessingException: File format is not supported
```

Original comment by `ogren.pe...@gmail.com` on 25 Oct 2013 at 10:27

**Comment by GoogleCodeExporter** [comment]
```
I have the same issue. com.drew.imaging.ImageProcessingException: File format 
is not supported
```

Original comment by `marc.so...@gmail.com` on 30 Oct 2013 at 9:51

**Comment by GoogleCodeExporter** [comment]
```
You should use version 2.7 which take into account PNG, GIF file ...
Unfortunately it was never release on code.google.com

I finally find the source on github at this URL : 
https://github.com/drewfarris/metadata-extractor
Feel free to download source zipped and compile it with Maven

I have tried it and it's working for PNG and GIF !!!
```

Original comment by `eckarath...@devoteam.com` on 8 Jul 2014 at 9:01

**Comment by GoogleCodeExporter** [comment]
```
Apologies all, yes this feature is available in an unreleased version which as 
@eckarath points out is available in source form.

This project has now migrated to GitHub, and you should download the source 
from the official repo at:

https://github.com/drewnoakes/metadata-extractor

Version 2.7.0 will be released in the next few weeks. Thank you for your 
patience.
```

Original comment by `drewnoakes` on 19 Nov 2014 at 5:38
- Changed state: **Started**

**Comment by GoogleCodeExporter** [comment]
```
Version 2.7.0 will be released this weekend on GitHub and will support PNG, GIF.
```

Original comment by `drewnoakes` on 5 Dec 2014 at 11:03
- Changed state: **Done**
